apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: justgram
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.5"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              subPath: pgdata
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: azure-managed-disk
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: LoadBalancer
  ports:
   - port: 5432
     targetPort: 5432   
  selector:
   app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: justgram-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: justgram-web
  template:
    metadata:
      labels:
        app: justgram-web
    spec:
      containers:
      - name: justgram-web
        image: "acrjustgram.azurecr.io/justgram:#{Build.BuildId}#"
        imagePullPolicy: Always
        command: ["/bin/bash", "-c"]
        args: ["python manage.py makemigrations; python manage.py migrate; gunicorn pubmed_project.wsgi:application --bind 0.0.0.0:80"]
        resources:
          limits:
            memory: "512Mi"
            cpu: "0.2"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: justgram-web
spec:
  type: LoadBalancer
  selector:
    app: justgram-web
  ports:
  - port: 80
    targetPort: 80