# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Azure Pipelines

stages:
- stage: BuildandPush
  jobs:
    - job: Build_Image
      steps:
      - task: Docker@2
        displayName: buildAndPush
        inputs:
          containerRegistry: WedoCR
          repository: justgram
      - task: CmdLine@2
        inputs:
          script: 'echo $(Build.BuildId)'

    - job: Replace_Tokens
      steps:
      - task: replacetokens@5
        displayName: 'Replace tokens in **/*.yaml'
        inputs:
          targetFiles: '**/*.yaml'
          encoding: 'auto'
          tokenPattern: 'default'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          actionOnNoFiles: 'continue'
          enableTransforms: false
          useLegacyPattern: false
          enableTelemetry: true
      - task: CmdLine@2
        inputs:
          script: 'echo $(Build.BuildId)'
      - publish: '$(Build.ArtifactStagingDirectory)'
        artifact: 'k8s'

- stage: Deploy
  dependsOn: BuildandPush
  jobs:
    - job: Deploy_k8s
      steps:
      - download: current
        artifact: 'k8s'
      - task: KubernetesManifest@0
        displayName: deploy
        inputs:
          kubernetesServiceConnection: 'k8s-wedo-test'
          manifests: '$(Build.ArtifactStagingDirectory)/k8s/aks-deployment.yaml'
      - task: CmdLine@2
        inputs:
          script: 'echo $(Build.BuildId)'
      
