# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Azure Pipelines

stages:
- stage: BuildandPush
  jobs:
    - job: Build_Image
      steps:
      - task: Docker@2
        displayName: buildAndPush
        inputs:
          containerRegistry: WedoCR
          repository: justgram
      - task: CmdLine@2
        inputs:
          script: 'echo $(Build.BuildId)'

    - job: Replace_Tokens
      steps:
      - task: replacetokens@5
        displayName: 'Replace tokens in **/*.yaml'
        inputs:
          targetFiles: '**/*.yaml'
          encoding: 'auto'
          tokenPattern: 'default'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          actionOnNoFiles: 'continue'
          enableTransforms: false
          useLegacyPattern: false
          enableTelemetry: true
      - task: CmdLine@2
        inputs:
          script: 'echo $(Build.BuildId)'
    - job: Publish_Artifact
      steps:
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Pipeline.Workspace)'
          artifact: 'k8s'
          publishLocation: 'pipeline'

- stage: Deploy_App
  jobs:
    - job: Download_Artifacts
      steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'k8s'
          targetPath: '$(Pipeline.Workspace)'

    - job: Deploy_K8s
      steps:
      - task: KubernetesManifest@0
        displayName: deploy
        inputs:
          kubernetesServiceConnection: 'k8s-wedo-test'
          manifests: '$(Pipeline.Workspace)/aks-deployment.yaml'
      - task: CmdLine@2
        inputs:
          script: 'echo $(Build.BuildId)'