# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Azure Pipelines

stages:
- stage: BuildandPush
  jobs:
    - job: Build_Image
      steps:
      - task: Docker@2
        displayName: buildAndPush
        inputs:
          containerRegistry: WedoCR
          repository: justgram

- stage: Deploy_App
  dependsOn: BuildandPush
  jobs:
    - job: 
      steps:
      - task: replacetokens@5
        displayName: 'Replace tokens in **/*.yaml'
        inputs:
          targetFiles: '**/*.yaml'
    - job: 
      steps:
      - task: KubernetesManifest@0
        displayName: deploy
        inputs:
          kubernetesServiceConnection: 'k8s-wedo-test'
          manifests: 'aks-deployment.yaml'

