version: '3.4'

services:
  db:
    image: postgres
    volumes: 
      - mydb:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=grammar
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  grammarchecker:
    image: justgram
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: ./Dockerfile
    command: >
        sh -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:80"
    ports:
      - 80:80
    depends_on:
      - db
