version: '3.4'

services:
  grammardb:
    image: postgres
    container_name: justgramdb
    volumes: 
      - mygrammardb:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=grammar
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  web:
    image: justgram
    container_name: justgram
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
        - DATABASE_NAME=grammar
        - DATABASE_USER=postgres
        - DATABASE_PASSWORD=postgres
        - DATABASE_HOSTNAME=grammardb
        - DATABASE_PORT=5432
    command: >
        sh -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:80"
    ports:
      - 80:80
    depends_on:
      - grammardb
volumes:
  mygrammardb: 